export const QUOTA_OPTIONS = [
    { id: 'AMPLA_CONCORRENCIA', label: 'Ampla Concorrência', description: 'Vagas sem critérios específicos de cota.' },
    { id: 'ESCOLA_PUBLICA', label: 'Escola Pública', description: 'Para quem cursou todo o ensino médio em escola pública.' },
    { id: 'BAIXA_RENDA', label: 'Baixa Renda', description: 'Para estudantes de baixa renda familiar, conforme critérios do edital.' },
    { id: 'PPI', label: 'PPI (Pretos, Pardos e Indígenas)', description: 'Para estudantes autodeclarados pretos, pardos ou indígenas.' },
    { id: 'PRETOS_E_PARDOS', label: 'Pretos e Pardos', description: 'Para estudantes autodeclarados pretos ou pardos.' },
    { id: 'INDIGENAS', label: 'Indígenas', description: 'Para estudantes indígenas, conforme critérios específicos do edital.' },
    { id: 'QUILOMBOLAS', label: 'Quilombolas', description: 'Para estudantes pertencentes a comunidades quilombolas.' },
    { id: 'PCD', label: 'Pessoa com Deficiência (PCD)', description: 'Para pessoas com deficiência, conforme laudo exigido no edital.' },
    { id: 'TRANS', label: 'Trans / Travesti', description: 'Para pessoas trans ou travestis, quando previsto pela instituição.' },
    { id: 'RURAL', label: 'Rural / Campo', description: 'Para estudantes oriundos de áreas rurais ou do campo.' },
    { id: 'AGRICULTURA_FAMILIAR', label: 'Agricultura Familiar', description: 'Para estudantes de famílias que vivem da agricultura familiar.' },
    { id: 'REFUGIADOS', label: 'Refugiados', description: 'Para pessoas com status de refugiado reconhecido no Brasil.' },
    { id: 'CIGANOS', label: 'Ciganos', description: 'Para estudantes pertencentes a comunidades ciganas.' },
    { id: 'AUTISMO', label: 'Autismo', description: 'Para pessoas no espectro autista, quando previsto no edital.' },
    { id: 'ALTAS_HABILIDADES', label: 'Altas Habilidades', description: 'Para estudantes com altas habilidades ou superdotação.' },
    { id: 'EJA_ENCCEJA', label: 'EJA / ENCCEJA', description: 'Para quem concluiu os estudos pelo EJA ou ENCCEJA.' },
    { id: 'PROFESSOR', label: 'Professor da Rede Pública', description: 'Para professores que atuam na rede pública de ensino.' },
    { id: 'MILITAR', label: 'Militares e Familiares', description: 'Para policiais, bombeiros, militares ou seus familiares, conforme regras específicas.' },
    { id: 'EFA', label: 'Escolas Família Agrícola (EFA)', description: 'Para egressos de Escolas Família Agrícola.' },
    { id: 'PRIVACAO_LIBERDADE', label: 'Privação de Liberdade', description: 'Para pessoas em privação de liberdade ou que cumprem medidas socioeducativas.' },
    { id: 'PCD_AUDITIVA', label: 'Deficiência Auditiva / Surdos', description: 'Para pessoas com deficiência auditiva, candidatos a cursos como Letras-Libras.' },
    { id: 'ESCOLA_PRIVADA_BOLSA_INTEGRAL', label: 'Escola Privada com Bolsa', description: 'Para quem estudou em escola privada com bolsa integral.' },
    { id: 'OUTROS_ESPECIFICO', label: 'Outros Critérios Específicos', description: 'Outros critérios de cota específicos não listados acima.' },
];
