// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aifzkybxhmefbirujvdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZnpreWJ4aG1lZmJpcnVqdmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1OTI5MjUsImV4cCI6MjA4NDE2ODkyNX0.YCnij78ps2si_zl_yT-XGcd9RpOjOht-u04ppSAbpM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});